name: rainforest_biz_project
description: ''
version: 0.1.0
author: akash91162@gmail.com
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: rainforestbizproject
  parentArtefactID: akash91162gmailcomteam
  buildSystem: wheel
  author: null
  createdAt: '2024-04-21 11:46:50'
pipelines:
  pipelines/enrich_accounts:
    name: enrich_accounts
    description: ''
    author: akash91162@gmail.com
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-04-21 11:46:50'
    datasets:
      inputs:
      - datasets/salesforce-Account
      - datasets/salesforce-Opportunity
      outputs:
      - datasets/enriched_accounts
    subgraphs: []
    dependencies: {}
datasets:
  datasets/salesforce-Opportunity:
    name: salesforce-Opportunity
    description: ''
    author: akash91162@gmail.com
    createdAt: '2024-04-21 11:53:20'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 11473
        datasetType: File
        description: ''
        author: akash91162@gmail.com
        createdAt: '2024-04-21 11:53:20'
  datasets/salesforce-Account:
    name: salesforce-Account
    description: ''
    author: akash91162@gmail.com
    createdAt: '2024-04-21 11:59:21'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 11473
        datasetType: File
        description: ''
        author: akash91162@gmail.com
        createdAt: '2024-04-21 11:59:21'
  datasets/enriched_accounts:
    name: enriched_accounts
    description: ''
    author: akash91162@gmail.com
    createdAt: '2024-04-21 12:18:24'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 11473
        datasetType: Database
        description: ''
        author: akash91162@gmail.com
        createdAt: '2024-04-21 12:18:24'
templates: {}
jobs:
  jobs/daily_Accounts:
    name: daily_Accounts
    description: ''
    fabricUID: 11473
    scheduler:
      Databricks: {}
    cloudProvider: null
    jobSize: small
    scheduleCron: 0 0 0 * * ? *
    timeout: null
    alerting:
      emails: akash91162@gmail.com
      onStart: true
      onSuccess: true
      onFailure: true
    pipelines:
    - pipelines/enrich_accounts
    jobClusterMode:
      clusterMode:
        Single: {}
      clusterId: null
    enabled: false
    createdAt: '2024-04-21 12:26:58'
    author: akash91162@gmail.com
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-04-21 11:46:50'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
subgraphs: {}
sqlModels: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-04-21T11:46:50.287495Z'
  name: plibMaven
  version: 7.1.88
  createdAt: '2024-04-21T11:46:50.287495Z'
  type: plibMaven
- modifiedAt: '2024-04-21T11:46:50.287495Z'
  name: plibPypi
  version: 1.8.15
  createdAt: '2024-04-21T11:46:50.287495Z'
  type: plibPypi
projectDependencies:
  '12654':
    projectUID: 12654
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12654.git&subPath=
    version: 0.2.6
    isDefault: true
    author: null
    createdAt: '2024-04-21 11:45:22'
  '12655':
    projectUID: 12655
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12655.git&subPath=
    version: 0.0.5
    isDefault: true
    author: null
    createdAt: '2024-04-21 11:45:22'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
